#!/usr/bin/env bash
# Configuring web-01 to have a HTTP RESPONSE HEADER
# these scripts are an upgrade from the web-server scripts...

# uncomment to see the script run in action
#set -x

echo -e "Updating and doing some minor checks...\n"
sudo apt-get update
sudo apt-get install -y nginx

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# creating new index
echo "Hello World!" | sudo tee /var/www/html/index.html

#Performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/solokool66 permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# create new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

#Custom HTTP Response Header
sudo sed -i "server_name _;/a add_header x-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Testing for syntax eror
sudo nginx -t

#Restart Nginx
sudo service nginx restart
