#!/usr/bin/env bash
# Server-01 Login commands

#Setting for the ssh-agent
eval $("ssh-agent")
# path to find file for private key
ssh-add ~/.ssh/school

# Username and IP Address
ssh ubuntu@54.226.23.119
